# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
SHM_CppArma <- function(y, mu, X, Rhat, N, nx, nt, index, muEta) {
    .Call('_modifiedPGEE_SHM_CppArma', PACKAGE = 'modifiedPGEE', y, mu, X, Rhat, N, nx, nt, index, muEta)
}

