// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pgee
Rcpp::List pgee(arma::vec y, arma::mat X, arma::vec b0, arma::vec nt, arma::vec pindex, std::string glmlink, std::string penalty, std::string corstr, double lambda, double eps, double tol, int maxit);
RcppExport SEXP _pseudoCure_pgee(SEXP ySEXP, SEXP XSEXP, SEXP b0SEXP, SEXP ntSEXP, SEXP pindexSEXP, SEXP glmlinkSEXP, SEXP penaltySEXP, SEXP corstrSEXP, SEXP lambdaSEXP, SEXP epsSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pindex(pindexSEXP);
    Rcpp::traits::input_parameter< std::string >::type glmlink(glmlinkSEXP);
    Rcpp::traits::input_parameter< std::string >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< std::string >::type corstr(corstrSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(pgee(y, X, b0, nt, pindex, glmlink, penalty, corstr, lambda, eps, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// gee
Rcpp::List gee(arma::vec y, arma::mat X, arma::vec b0, arma::vec nt, std::string glmlink, std::string corstr, double tol, int maxit);
RcppExport SEXP _pseudoCure_gee(SEXP ySEXP, SEXP XSEXP, SEXP b0SEXP, SEXP ntSEXP, SEXP glmlinkSEXP, SEXP corstrSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< std::string >::type glmlink(glmlinkSEXP);
    Rcpp::traits::input_parameter< std::string >::type corstr(corstrSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(gee(y, X, b0, nt, glmlink, corstr, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// pgeeCV
arma::mat pgeeCV(arma::vec y, arma::mat X, arma::vec b0, arma::vec nt, arma::vec pindex, std::string glmlink, std::string penalty, std::string corstr, int nCV, arma::vec lambda, double eps, double tol, int maxit);
RcppExport SEXP _pseudoCure_pgeeCV(SEXP ySEXP, SEXP XSEXP, SEXP b0SEXP, SEXP ntSEXP, SEXP pindexSEXP, SEXP glmlinkSEXP, SEXP penaltySEXP, SEXP corstrSEXP, SEXP nCVSEXP, SEXP lambdaSEXP, SEXP epsSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type b0(b0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type pindex(pindexSEXP);
    Rcpp::traits::input_parameter< std::string >::type glmlink(glmlinkSEXP);
    Rcpp::traits::input_parameter< std::string >::type penalty(penaltySEXP);
    Rcpp::traits::input_parameter< std::string >::type corstr(corstrSEXP);
    Rcpp::traits::input_parameter< int >::type nCV(nCVSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(pgeeCV(y, X, b0, nt, pindex, glmlink, penalty, corstr, nCV, lambda, eps, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// pseudoKM
arma::vec pseudoKM(arma::vec Time, arma::vec censor);
RcppExport SEXP _pseudoCure_pseudoKM(SEXP TimeSEXP, SEXP censorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Time(TimeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor(censorSEXP);
    rcpp_result_gen = Rcpp::wrap(pseudoKM(Time, censor));
    return rcpp_result_gen;
END_RCPP
}
// pseudoKM1
arma::mat pseudoKM1(arma::vec Time, arma::vec censor, arma::vec Q);
RcppExport SEXP _pseudoCure_pseudoKM1(SEXP TimeSEXP, SEXP censorSEXP, SEXP QSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Time(TimeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor(censorSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Q(QSEXP);
    rcpp_result_gen = Rcpp::wrap(pseudoKM1(Time, censor, Q));
    return rcpp_result_gen;
END_RCPP
}
// fastKM
arma::mat fastKM(arma::vec Time, arma::vec censor);
RcppExport SEXP _pseudoCure_fastKM(SEXP TimeSEXP, SEXP censorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Time(TimeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor(censorSEXP);
    rcpp_result_gen = Rcpp::wrap(fastKM(Time, censor));
    return rcpp_result_gen;
END_RCPP
}
// testMZ
Rcpp::List testMZ(arma::vec Time, arma::vec censor);
RcppExport SEXP _pseudoCure_testMZ(SEXP TimeSEXP, SEXP censorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Time(TimeSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type censor(censorSEXP);
    rcpp_result_gen = Rcpp::wrap(testMZ(Time, censor));
    return rcpp_result_gen;
END_RCPP
}
// fastDabrowska
double fastDabrowska(double tx, double ty, arma::vec x, arma::vec y, arma::vec dx, arma::vec dy, arma::mat L);
RcppExport SEXP _pseudoCure_fastDabrowska(SEXP txSEXP, SEXP tySEXP, SEXP xSEXP, SEXP ySEXP, SEXP dxSEXP, SEXP dySEXP, SEXP LSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tx(txSEXP);
    Rcpp::traits::input_parameter< double >::type ty(tySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dx(dxSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dy(dySEXP);
    Rcpp::traits::input_parameter< arma::mat >::type L(LSEXP);
    rcpp_result_gen = Rcpp::wrap(fastDabrowska(tx, ty, x, y, dx, dy, L));
    return rcpp_result_gen;
END_RCPP
}
// fastL
arma::mat fastL(arma::vec x1, arma::vec y1, arma::vec dx1, arma::vec dy1);
RcppExport SEXP _pseudoCure_fastL(SEXP x1SEXP, SEXP y1SEXP, SEXP dx1SEXP, SEXP dy1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dx1(dx1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dy1(dy1SEXP);
    rcpp_result_gen = Rcpp::wrap(fastL(x1, y1, dx1, dy1));
    return rcpp_result_gen;
END_RCPP
}
// fastTau2
double fastTau2(arma::vec x1, arma::vec y1, arma::vec dx1, arma::vec dy1);
RcppExport SEXP _pseudoCure_fastTau2(SEXP x1SEXP, SEXP y1SEXP, SEXP dx1SEXP, SEXP dy1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dx1(dx1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dy1(dy1SEXP);
    rcpp_result_gen = Rcpp::wrap(fastTau2(x1, y1, dx1, dy1));
    return rcpp_result_gen;
END_RCPP
}
// pseudoTau
arma::vec pseudoTau(arma::vec x1, arma::vec y1, arma::vec dx1, arma::vec dy1);
RcppExport SEXP _pseudoCure_pseudoTau(SEXP x1SEXP, SEXP y1SEXP, SEXP dx1SEXP, SEXP dy1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x1(x1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y1(y1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dx1(dx1SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type dy1(dy1SEXP);
    rcpp_result_gen = Rcpp::wrap(pseudoTau(x1, y1, dx1, dy1));
    return rcpp_result_gen;
END_RCPP
}
