# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pgee <- function(y, X, b0, nt, pindex, glmlink, penalty, corstr, lambda, eps, tol, maxit) {
    .Call(`_pseudoCure_pgee`, y, X, b0, nt, pindex, glmlink, penalty, corstr, lambda, eps, tol, maxit)
}

gee <- function(y, X, b0, nt, glmlink, corstr, tol, maxit) {
    .Call(`_pseudoCure_gee`, y, X, b0, nt, glmlink, corstr, tol, maxit)
}

pgeeCV <- function(y, X, b0, nt, pindex, glmlink, penalty, corstr, nCV, lambda, eps, tol, maxit) {
    .Call(`_pseudoCure_pgeeCV`, y, X, b0, nt, pindex, glmlink, penalty, corstr, nCV, lambda, eps, tol, maxit)
}

pseudoKM <- function(Time, censor) {
    .Call(`_pseudoCure_pseudoKM`, Time, censor)
}

pseudoKM1 <- function(Time, censor, Q) {
    .Call(`_pseudoCure_pseudoKM1`, Time, censor, Q)
}

fastKM <- function(Time, censor) {
    .Call(`_pseudoCure_fastKM`, Time, censor)
}

#' @noRd
fastDabrowska <- function(tx, ty, x, y, dx, dy, L) {
    .Call(`_pseudoCure_fastDabrowska`, tx, ty, x, y, dx, dy, L)
}

#' @noRd
fastL <- function(x1, y1, dx1, dy1) {
    .Call(`_pseudoCure_fastL`, x1, y1, dx1, dy1)
}

#' @noRd
fastTau2 <- function(x1, y1, dx1, dy1) {
    .Call(`_pseudoCure_fastTau2`, x1, y1, dx1, dy1)
}

#' @noRd
pseudoTau <- function(x1, y1, dx1, dy1) {
    .Call(`_pseudoCure_pseudoTau`, x1, y1, dx1, dy1)
}

