# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pgee <- function(y, X, b0, nt, pindex, glmlink, penalty, corstr, lambda, eps, tol, maxit) {
    .Call('_pseudoCure_pgee', PACKAGE = 'pseudoCure', y, X, b0, nt, pindex, glmlink, penalty, corstr, lambda, eps, tol, maxit)
}

gee <- function(y, X, b0, nt, glmlink, corstr, tol, maxit) {
    .Call('_pseudoCure_gee', PACKAGE = 'pseudoCure', y, X, b0, nt, glmlink, corstr, tol, maxit)
}

pgeeCV <- function(y, X, b0, nt, pindex, glmlink, penalty, corstr, nCV, lambda, eps, tol, maxit) {
    .Call('_pseudoCure_pgeeCV', PACKAGE = 'pseudoCure', y, X, b0, nt, pindex, glmlink, penalty, corstr, nCV, lambda, eps, tol, maxit)
}

pseudoKM <- function(Time, censor) {
    .Call('_pseudoCure_pseudoKM', PACKAGE = 'pseudoCure', Time, censor)
}

pseudoKM1 <- function(Time, censor, Q) {
    .Call('_pseudoCure_pseudoKM1', PACKAGE = 'pseudoCure', Time, censor, Q)
}

